### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by izraelov** [wdkwyf/TeethDectcotor#1]
Please can you get a tutorial on how to run the program?
---/
  File "D:\Projects\Python\TensorFlowModels\research\object_detection\train.py", line 49, in <module>
    from object_detection import trainer
ModuleNotFoundError: No module named 'object_detection'
---/
Thanks

**Comment by ArlexDu** [comment]
Hi,izraelov
We have updated Readme in English version. This Project is based on TensorFlow Models, so you need to install TensorFlow Models in your computer , Model's git is https://github.com/tensorflow/models, and My main reference is this blog https://towardsdatascience.com/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9 to complete the project.I hope these will be helpful.

**Comment by izraelov** [comment]
Thanks for the response.
After I installed TensorFlow models
when i try to to  do : 
python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record
error:
Traceback (most recent call last):
  File "generate_tfrecord.py", line 108, in <module>
    main()
  File "generate_tfrecord.py", line 101, in main
    tf_example = create_tf_example(group, imgpath)
  File "generate_tfrecord.py", line 66, in create_tf_example
    classes_text.append(row['class'].encode('utf8'))
AttributeError: 'int' object has no attribute 'encode'

**Comment by ArlexDu** [comment]
I have changed the file and you need just run generate_tfrecord.py without any params.

**Comment by izraelov** [comment]
Same problem. Even without param
` C:\tensorflow1\models\research\object_detection>python generate_tf_record.py
C:\Users\itayi\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "generate_tf_record.py", line 108, in <module>
    main()
  File "generate_tf_record.py", line 101, in main
    tf_example = create_tf_example(group, imgpath)
  File "generate_tf_record.py", line 66, in create_tf_example
    classes_text.append(row['class'].encode('utf8'))
AttributeError: 'int' object has no attribute 'encode'`

**Comment by ArlexDu** [comment]
I got it, you should run generate_tf_record.py  which in my project. First run xml_to_csv.py then run generate_tf_generate.I recommend you to open this project in PyCharm...

**Comment by izraelov** [comment]
I've been a few days trying to run it.(also PyCharm)
but without success.
If you have time, I would be happy if you upload a brief guide on how to activate the system.
Thanks.

**Comment by ArlexDu** [comment]
Hi,Can you run the tensorflow object detection demo successfully? and before you run the .bat file, make sure these paths which in .bat file are right in your machine.

**Comment by izraelov** [comment]
I got on the problem.
I managed to run the model. Thanks
classes_text.append(row['class'].encode('utf8')) To classes_text.append(str(row['class']).encode('utf8'))
